version: "3"
services:
  fleet-api:
    image: local-fleet-api
    environment:
      NODE_PORT: 3001
      MONGO_DB_URI: mongodb://mongodb:27017/fleet-db
      TOKEN_SECRET: 09f26e402586e2faa8da4c98a35f1b20d6b033c6097befa8be3486a829587fe2f90a832bd3ff9d42710a4da095a2ce285b009f0c3730cd9b8e1af3eb84df6611
      TOKEN_TTL: 86400
      REFRESH_TOKEN_TTL: 172800
      DRIVER_API_KEY: f27f9f10-d82b-4ad6-ba9e-58862e3c9b6f
      OPERATOR_API_KEY: 1be8d583-bfdf-46f8-997f-0db783ba2a9c
    ports:
      - 3001:80
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0.5
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - mongodb-volume:/data/db
    ports:
      - 23017:27017
volumes:
  mongodb-volume:
